### ISSUE TITLE
Configuration: XML, Yaml or Annotations?

### ISSUE THREAD

**Issue by leevigraham** [newism/symfony2-standard-template#6]
Yaml: 
- Easy to read. 
- Easy to write. 
- Separates config from code.
- Not sure about IDE support

XML: 
- Separates config from code. 
- Can be validated and includes IDE auto completion hints

Annotations: 
- Some bundles only support annotations. 
- Harder to maintain. 
- Configuration in context
- Poses an issue for auto generating code (entities)

Ping @ianbelcher @iainsaxon

**Comment by ghost** [comment]
My personal preference (at the moment) is yaml, but it does have it's shortcomings in comparison to xml. I do find xml harder to read but it 'feels' like the proper way to go.

Annotations are the thorn in the side. As you've said, many bundles only support annotations, but again I 'feel' getting away from them is the right thing. For a larger site, routing would be much harder using annotations and I'm predicting Nelmio\ApiDocBundle will be a little more difficult to keep up to date correctly using annotations.

**Comment by leevigraham** [comment]
So lets go with yml for everything except controller annotations for bundles:

| What? | Filename | Notes |
| --- | --- | --- |
| Config | config.yml |  |
| Services | services.yml |  |
| Routes | routes.yml | Routes should be split into files for each controller |
| Validation | validation.yml | http://stackoverflow.com/a/16759153/1982031 |
| Doctrine Metadata | SomeEntity.orm.yml | http://symfony.com/doc/current/book/doctrine.html#add-mapping-information |
| HATEOS representations |  | http://hateoas-php.org/#yaml |
| JMS Serialiser |  | http://jmsyst.com/libs/serializer/master/reference/xml_reference |
| Controller Annotations for bundles |  |  |

**Comment by leevigraham** [comment]
No objections means this is closed. Added to the wiki: https://github.com/newism/symfony2-standard-template/wiki/Annotations-vs-YAML-vs-XML
